apiVersion: v1

kind: Service

metadata:
  name: nginx-service  

spec:
  selector:
    app: nginx     #send traffic to pods labeled app=nginx

  ports:
    - protocol: TCP
      port: 80         #service port
      targetPort: 80   #container port

  type: NodePort       #alllow us to access the service throught the kubernetes node